name = "nullhell"
author = "Monachrome"
version = "1.0.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3cb585b4656e05086c5c7d6237bd8a4aaa6e3790c80865a0b5f60b93e66cbae2"

[versions]
forge = "47.4.6"
minecraft = "1.20.1"
