name = "nullhell"
author = "Monachrome"
version = "1.0.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "94ffde6db19a8c9a8d714e1d7d7373996c21d06d1fab9022b71433f0ea390a6a"

[versions]
forge = "47.4.6"
minecraft = "1.20.1"
