name = "nullhell"
author = "Monachrome"
version = "1.0.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "15e864b5aa0ed79c8c63764cbadfaf0dcbd3b87a335b0ba759aa9e92cb425e0b"

[versions]
forge = "47.4.6"
minecraft = "1.20.1"
